[VELRM-1186] Fix PHP 7.4 support
rentsoft/PHPExcel pull request #1
Opened 2020-06-30 06:55 UTC by nartzis

## Тест план

- [ ] Убедиться, что этот фикс починил много тестов в этой сборке http://ci.prod.velvica.com:8111/viewLog.html?buildId=96458&buildTypeId=DEV_OnPremisesMasterPhp74

## После мёрджа
- [ ] @nartzis дожен обновить composer в репозитории RS

2020-07-02 09:23 UTC, IgorVodka requested changes

2020-07-02 09:23 UTC, IgorVodka commented on Classes/PHPExcel/Cell/DefaultValueBinder.php
> +		} elseif (((string) $pValue){0} === '=' && strlen($pValue) > 1) {
а что за фигурные скобки?

2020-07-02 09:29 UTC, nartzis commented on Classes/PHPExcel/Cell/DefaultValueBinder.php
> +		} elseif (((string) $pValue){0} === '=' && strlen($pValue) > 1) {
Обращение по индексу видимо, это вопрос к авторам PHP Excel

2020-07-02 12:26 UTC, IgorVodka commented on Classes/PHPExcel/Cell/DefaultValueBinder.php
> +		} elseif (((string) $pValue){0} === '=' && strlen($pValue) > 1) {
В [PHP 7.4](https://wiki.php.net/rfc/deprecate_curly_braces_array_access) так делать уже не рекомендуется. Нужно поправить.

2020-07-02 12:27 UTC, IgorVodka commented on Classes/PHPExcel/Cell/DefaultValueBinder.php
> +		} elseif (((string) $pValue){0} === '=' && strlen($pValue) > 1) {
В PHP 7.4 так делать уже [не рекомендуется](https://wiki.php.net/rfc/deprecate_curly_braces_array_access). Нужно поправить.

2020-07-06 06:06 UTC, nartzis commented on Classes/PHPExcel/Cell/DefaultValueBinder.php
> +		} elseif (((string) $pValue){0} === '=' && strlen($pValue) > 1) {
Поправил

2020-07-06 07:37 UTC, IgorVodka approved these changes

2020-07-06 07:37 UTC, merged